//A CALL BACK FUNCTION IS A FUNCTION THAT PASSES AS AN ARGUMENT TO ANOTHER FUNCTION.
//WHY WE CAN USE CALLBACK FUNCTION?
//ANS:-YE BASICALLY ASYNCHRONOUS PROGRAMMING KE CASE ME USE HOTA HAI.MAAN LO KOI INSTRUCTION HMLOG EXECUTE KRA RHE HAI
// AB USKO EXECUTE HONE ME TIME LG RHA HAI US CASE ME ASYNCHRONOUS ME KYA HOTA HAI USKO PARALLEL PROCESSING KRWA DETE 
// HAI AUR USKE BAAD WALE CODE KO EXECUTE KR DETE HAI.AISA NHI HO ASYNCHRONOUS KE CASE ME ISLIYE HMLOG CALLBACK FUNCTION USE KRTE HAI.

//IN THIS WHEN ANOTHER FUNCTION HAS FINISHED EXECUTING THEN CALLBACK FUNCTION WILL BE EXECUTED.
//CALL ME BACK MTLB TERA KAAM HO JAYE TO FIR MUJHE CALL KR.
//const a=(name,call)=>{
 //   console.log(`I AM BUSY RIGHT NOW. I AM SPEAKING WITH ${name}.I WIILL CALL YOU LATER`)
 //   call()
//}
//const b=()=>{
 //   console.log("OK WHEN YOU ARE FREE THEN CALL ME")
//}
//a("BHAI",b)


//PAHLE JB FUNCTION KO CALL KRTE THE TO USKE ARGUMENT ME HMLOG VALUE PASS KRTE THE
//LEKIN AB HMLOG USKE ARGUMENT ME FUNCTION PASS KRENGE.
//EXAMPLE 1.
/*function add(a,b){
    console.log(a+b)
}
add(4,4) //IN THIS WE PASSES VALUE AS AN ARGUMENT.*/


//EXAMPLE 2.
/*function name(){
    console.log("Rohan Raj")
}
function add(a,b,call){
    console.log(a+b)
    call()
}
add(4,4,name) 1. IN THIS CASE WE PASSES FUNCTION AS AN ARGUMENT. 2. AB KYA HOGA YHA PE EK QUESTION ARISE HOTA HAI KI
HMLOG TO DIRECT FUNCTION KO V TO CALL KR SKTE THE.
function name(){
    console.log("Rohan Raj")
}
function add(a,b,call){
    name()
    console.log(a+b)
    call()
}
add(4,4,name)//3. AGAR MERA 2 FUNCTION HAI TO USME MERA DIRECT CALL EK HI FUNCTION HOGA US CASE ME KYA KRENGE.
function name(){
    console.log("Rohan Raj")
}
function bhai(){
    console.log("Rahul Raj")
}
function add(a,b,call){
    console.log(a+b)
    call()
}
add(4,4,name)
add(4,4,bhai)4. AB KYA HOGA KI HMLOG FUNCTION KO PARAMETER ME PASS KR DETE HAI AUR  FUNCTION CALL KE TIME USME VALUE
LE KR PRINT KRWA DETE HAI.
function add(a,b,call){
    console.log(a+b,call)
}
let name="Rohan Raj"
add(4,4,name)*/